KyoriPowered/adventure

- src/main/java/net/kyori/text/LegacyComponent.java
Allows the use of both `§` and `&`.
> Allow the legacy character to be specified in LegacyComponent

- src/main/java/net/kyori/text/serializer/LegacyComponentSerializerImpl.java
- src/test/java/net/kyori/text/serializer/ComponentSerializerTest.java
> legacy: fix serialisation

- src/main/java/net/kyori/text/AbstractBuildableComponent.java
- src/main/java/net/kyori/text/BuildableComponent.java
- src/main/java/net/kyori/text/serializer/LegacyComponentSerializerImpl.java
- src/test/java/net/kyori/text/serializer/ComponentSerializerTest.java
> Fix consecutive color code parsing

- src/main/java/net/kyori/text/serializer/LegacyComponentSerializerImpl.java
- src/test/java/net/kyori/text/serializer/LegacyComponentSerializerTest.java
Fixes this issue https://i.imgur.com/OjGTwa6.png
> Fix handling of &r in the legacy component deserializer

- src/main/java/net/kyori/text/serializer/ComponentSerializers.java
- src/main/java/net/kyori/text/serializer/PlainComponentSerializer.java
- src/test/java/net/kyori/text/serializer/PlainComponentSerializerTest.java
Merges f2307661091c1df788bfc85763324b0cc64348eb into branch 1.11
> Merge plain component serializer into 1.11 branch

- src/main/java/net/kyori/text/serializer/LegacyComponentSerializerImpl.java
- src/test/java/net/kyori/text/serializer/LegacyComponentSerializerTest.java
> Fix legacy serializer when text changes from reset to a color (fixes #17)

- readme.md
Similar to #22 but for the 1.11-branch
> fixing typos in 1.11 branch

- serializer-jackson/build.gradle
- serializer-jackson/src/main/java/net/kyori/text/serializer/jackson/BlockNbtComponentPosDeserializer.java
- serializer-jackson/src/main/java/net/kyori/text/serializer/jackson/BlockNbtComponentPosSerializer.java
- serializer-jackson/src/main/java/net/kyori/text/serializer/jackson/ClassKey.java
- serializer-jackson/src/main/java/net/kyori/text/serializer/jackson/ComponentDeserializer.java
- serializer-jackson/src/main/java/net/kyori/text/serializer/jackson/ComponentSerializer.java
- serializer-jackson/src/main/java/net/kyori/text/serializer/jackson/JacksonComponentSerializer.java
- serializer-jackson/src/main/java/net/kyori/text/serializer/jackson/JacksonDeserializeException.java
- serializer-jackson/src/main/java/net/kyori/text/serializer/jackson/JacksonSerializeException.java
- serializer-jackson/src/main/java/net/kyori/text/serializer/jackson/KyoriDeserializers.java
- serializer-jackson/src/main/java/net/kyori/text/serializer/jackson/KyoriTextModule.java
- serializer-jackson/src/main/java/net/kyori/text/serializer/jackson/NameMapDeserializer.java
- serializer-jackson/src/main/java/net/kyori/text/serializer/jackson/NameMapSerializer.java
- serializer-jackson/src/main/java/net/kyori/text/serializer/jackson/StyleDeserializer.java
- serializer-jackson/src/main/java/net/kyori/text/serializer/jackson/StyleSerializer.java
- serializer-jackson/src/main/java/net/kyori/text/serializer/jackson/TextColorWrapper.java
- serializer-jackson/src/test/java/net/kyori/text/serializer/jackson/AbstractComponentTest.java
- serializer-jackson/src/test/java/net/kyori/text/serializer/jackson/AbstractSerializeDeserializeTest.java
- serializer-jackson/src/test/java/net/kyori/text/serializer/jackson/BlockNbtComponentTest.java
- serializer-jackson/src/test/java/net/kyori/text/serializer/jackson/ComponentSerializerTest.java
- serializer-jackson/src/test/java/net/kyori/text/serializer/jackson/EntityNbtComponentTest.java
- serializer-jackson/src/test/java/net/kyori/text/serializer/jackson/KeybindComponentTest.java
- serializer-jackson/src/test/java/net/kyori/text/serializer/jackson/KyoriDeserializersTest.java
- serializer-jackson/src/test/java/net/kyori/text/serializer/jackson/ScoreComponentTest.java
- serializer-jackson/src/test/java/net/kyori/text/serializer/jackson/SelectorComponentTest.java
- serializer-jackson/src/test/java/net/kyori/text/serializer/jackson/StyleTest.java
- serializer-jackson/src/test/java/net/kyori/text/serializer/jackson/TextComponentTest.java
- serializer-jackson/src/test/java/net/kyori/text/serializer/jackson/TranslatableComponentTest.java
- settings.gradle
https://github.com/KyoriPowered/text/pull/42, but squashed
> Add jackson

- api/src/main/java/net/kyori/text/ComponentBuilders.java
- api/src/main/java/net/kyori/text/StorageNbtComponent.java
- api/src/main/java/net/kyori/text/StorageNbtComponentImpl.java
- api/src/test/java/net/kyori/text/StorageNbtComponentTest.java
- serializer-gson/src/main/java/net/kyori/text/serializer/gson/GsonComponentSerializer.java
- serializer-gson/src/test/java/net/kyori/text/serializer/gson/StorageNbtComponentTest.java
Look at 19w39a
Signed-off-by: liach <liach@users.noreply.github.com>
> Added storage nbt component

- api/src/main/java/net/kyori/adventure/text/format/Style.java
- api/src/test/java/net/kyori/adventure/text/format/StyleTest.java
- text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/StyleSerializer.java
Fonts need to default to null to be able to be merged properly.
Add in a merge strategy for fonts as well.
tested working ingame :)
> Flesh out font handling

- api/src/main/java/net/kyori/adventure/text/format/TextColor.java
- api/src/main/java/net/kyori/adventure/text/format/TextColorImpl.java
- api/src/test/java/net/kyori/adventure/text/format/TextColorTest.java
makes working with the colors just a touch easier
I'd like to add in some things for lighten/darken and converting from HSV colors eventually, but this is enough to get things going.
> Add methods to get the individual components of a text color

- readme.md
> start updating readme for 4.0

- text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/GsonComponentSerializer.java
- text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/GsonComponentSerializerImpl.java
- text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/LegacyHoverEventSerializer.java
- text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/StyleSerializer.java
A little unfortunate, but it works without a hard nbt dependency :)
> Legacy hover event support

- .checkstyle/suppressions.xml
fix checkstyle suppressions to work on windows as well.
> path normalization who?

- api/src/main/java/net/kyori/adventure/nbt/api/BinaryTagHolder.java
- nbt/src/main/java/net/kyori/adventure/nbt/BinaryTagIO.java
- nbt/src/main/java/net/kyori/adventure/nbt/ByteBinaryTag.java
- nbt/src/main/java/net/kyori/adventure/nbt/TagStringIO.java
- nbt/src/main/java/net/kyori/adventure/nbt/TagStringReader.java
- nbt/src/main/java/net/kyori/adventure/nbt/TagStringWriter.java
- nbt/src/main/java/net/kyori/adventure/nbt/Tokens.java
- nbt/src/test/java/net/kyori/adventure/nbt/StringIOTest.java
These changes cover a few omissions from the original reader, add in explicit support for the legacy (pre-1.13) format, and add a first pass at pretty-printing.
> A few tweaks to the SNBT reader + writer

- api/src/main/java/net/kyori/adventure/text/BlockNBTComponent.java
- api/src/main/java/net/kyori/adventure/text/BlockNBTComponentImpl.java
- api/src/test/java/net/kyori/adventure/text/BlockNBTComponentTest.java
- text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/BlockNBTComponentPosSerializer.java
- text-serializer-gson/src/test/java/net/kyori/adventure/text/serializer/gson/BlockNBTComponentTest.java
since we're wanting to use it in a few places
> Extract BlockNBTComponent position parsing from gson serializer

- text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerImpl.java
- text-serializer-legacy/src/test/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerTest.java
- text-serializer-legacy/src/test/java/net/kyori/adventure/text/serializer/legacy/LinkingLegacyComponentSerializerTest.java
Fixes #92 (at least I hope)
I *think* I have some understanding of the logic here, and the tests pass, so hopefully it doesn't cause more issues.
> Correctly handle resets followed by more styling

- api/src/main/java/net/kyori/adventure/bossbar/BossBar.java
- api/src/main/java/net/kyori/adventure/bossbar/package-info.java
- api/src/main/java/net/kyori/adventure/inventory/package-info.java
- api/src/main/java/net/kyori/adventure/key/package-info.java
- api/src/main/java/net/kyori/adventure/nbt/package-info.java
- api/src/main/java/net/kyori/adventure/sound/package-info.java
- nbt/src/main/java/net/kyori/adventure/nbt/BinaryTagIO.java
- nbt/src/main/java/net/kyori/adventure/nbt/CompoundBinaryTag.java
- nbt/src/main/java/net/kyori/adventure/nbt/ListBinaryTag.java
- nbt/src/main/java/net/kyori/adventure/nbt/package-info.java
- readme.md
let's make things easier to understand!
> beginning a documentation pass

- api/src/main/java/net/kyori/adventure/nbt/api/BinaryTagHolderImpl.java
- api/src/main/java/net/kyori/adventure/text/event/HoverEvent.java
- api/src/test/java/net/kyori/adventure/text/event/HoverEventTest.java
- api/src/test/java/net/kyori/adventure/translation/TranslationRegistryTest.java
- build.gradle
- text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/ShowEntitySerializer.java
- text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/ShowItemSerializer.java
- text-serializer-gson/src/test/java/net/kyori/adventure/text/serializer/gson/StyleTest.java
- text-serializer-gson/src/test/java/net/kyori/adventure/text/serializer/gson/TranslatableComponentTest.java
few little things that were annoying, commits have the details.
> A few misc tweaks

- .checkstyle/checkstyle.xml
- .checkstyle/suppressions.xml
- api/src/main/java/net/kyori/adventure/bossbar/package-info.java
- api/src/main/java/net/kyori/adventure/inventory/Book.java
- api/src/main/java/net/kyori/adventure/text/format/Style.java
- api/src/main/java/net/kyori/adventure/text/format/StyleBuilderApplicable.java
- api/src/main/java/net/kyori/adventure/text/format/TextColor.java
- api/src/main/java/net/kyori/adventure/translation/TranslationRegistry.java
- build.gradle
- nbt/src/main/java/net/kyori/adventure/nbt/CharBuffer.java
- nbt/src/main/java/net/kyori/adventure/nbt/StringTagParseException.java
- nbt/src/main/java/net/kyori/adventure/nbt/TagStringReader.java
- nbt/src/main/java/net/kyori/adventure/nbt/TagStringWriter.java
- nbt/src/main/java/net/kyori/adventure/nbt/Tokens.java
- serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/ConfigurateComponentSerializer.java
There were a few things that needed fixing up from this -- all updated within the PR.
> Checkstyle checks for Javadoc

- api/src/main/java/net/kyori/adventure/audience/Audience.java
- api/src/main/java/net/kyori/adventure/audience/EmptyAudience.java
- api/src/main/java/net/kyori/adventure/audience/ForwardingAudience.java
- api/src/main/java/net/kyori/adventure/identity/Identified.java
- api/src/main/java/net/kyori/adventure/identity/Identities.java
- api/src/main/java/net/kyori/adventure/identity/Identity.java
- api/src/main/java/net/kyori/adventure/identity/IdentityImpl.java
- api/src/main/java/net/kyori/adventure/text/event/ClickEvent.java
- api/src/main/java/net/kyori/adventure/text/event/HoverEvent.java
- api/src/main/java/net/kyori/adventure/text/format/StyleImpl.java
- api/src/main/java/net/kyori/adventure/translation/TranslationRegistryImpl.java
- api/src/test/java/net/kyori/adventure/identity/IdentityTest.java
`Identified` is designed to be implemented by `Player`
> Identities

- api/src/main/java/net/kyori/adventure/audience/ForwardingAudience.java
- build.gradle
This fixes KyoriPowered/adventure-platform#34
> 4.1.1: fix forwarding audience overloads

- .gitignore
- build.gradle
- serializer-configurate4/build.gradle
- serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/BlockNBTPosSerializer.java
- serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/BookTypeSerializer.java
- serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/ComponentTypeSerializer.java
- serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/ConfigurateComponentSerializer.java
- serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/ConfigurateComponentSerializerImpl.java
- serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/DurationSerializer.java
- serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/HoverEventShowEntitySerializer.java
- serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/HoverEventShowItemSerializer.java
- serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/IndexSerializer.java
- serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/KeySerializer.java
- serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/SoundSerializer.java
- serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/SoundStopSerializer.java
- serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/StyleSerializer.java
- serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/TextColorSerializer.java
- serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/TitleSerializer.java
- serializer-configurate4/src/test/java/net/kyori/adventure/serializer/configurate4/BookSerializerTest.java
- serializer-configurate4/src/test/java/net/kyori/adventure/serializer/configurate4/ComponentSerializerTest.java
- serializer-configurate4/src/test/java/net/kyori/adventure/serializer/configurate4/ConfigurateTestBase.java
- serializer-configurate4/src/test/java/net/kyori/adventure/serializer/configurate4/HoverEventSerializersTest.java
- serializer-configurate4/src/test/java/net/kyori/adventure/serializer/configurate4/ScalarSerializersTest.java
- serializer-configurate4/src/test/java/net/kyori/adventure/serializer/configurate4/SoundSerializersTest.java
- serializer-configurate4/src/test/java/net/kyori/adventure/serializer/configurate4/StyleSerializerTest.java
- serializer-configurate4/src/test/java/net/kyori/adventure/serializer/configurate4/TitleSerializerTest.java
- settings.gradle
Update existing configurate serializers for Configurate 4
Will be updated as necessary for Configurate changes.
> configurate4: Initial port

- text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer.java
- text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerImpl.java
> text-serializer-legacy: allow specifying custom url pattern

- api/src/main/java/net/kyori/adventure/text/TextReplacementRenderer.java
- api/src/test/java/net/kyori/adventure/text/TextComponentTest.java
> api: Fix handling of first replacements in child components

- text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/ComponentSerializerImpl.java
- text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/GsonComponentSerializerImpl.java
- text-serializer-gson/src/test/java/net/kyori/adventure/text/serializer/gson/GsonComponentSerializerTest.java
> text-serializer-gson: Don't deserialize into "null"

- .gitignore
- bom/build.gradle
- build.gradle
- settings.gradle
https://docs.gradle.org/current/userguide/java_platform_plugin.html#java_platform_plugin
> build: Add a bom for version alignment across submodules

- api/build.gradle
- api/src/main/java/net/kyori/adventure/audience/ForwardingAudience.java
- api/src/main/java/net/kyori/adventure/bossbar/BossBar.java
- api/src/main/java/net/kyori/adventure/bossbar/BossBarImpl.java
- api/src/main/java/net/kyori/adventure/bossbar/HackyBossBarPlatformBridge.java
- api/src/main/java/net/kyori/adventure/inventory/Book.java
- api/src/main/java/net/kyori/adventure/key/Key.java
- api/src/main/java/net/kyori/adventure/key/KeyImpl.java
- api/src/main/java/net/kyori/adventure/text/BlockNBTComponent.java
- api/src/main/java/net/kyori/adventure/text/Component.java
- api/src/main/java/net/kyori/adventure/text/ComponentBuilder.java
- api/src/main/java/net/kyori/adventure/text/ComponentBuilderApplicable.java
- api/src/main/java/net/kyori/adventure/text/ComponentLike.java
- api/src/main/java/net/kyori/adventure/text/EntityNBTComponent.java
- api/src/main/java/net/kyori/adventure/text/KeybindComponent.java
- api/src/main/java/net/kyori/adventure/text/NBTComponent.java
- api/src/main/java/net/kyori/adventure/text/NBTComponentBuilder.java
- api/src/main/java/net/kyori/adventure/text/ScoreComponent.java
- api/src/main/java/net/kyori/adventure/text/SelectorComponent.java
- api/src/main/java/net/kyori/adventure/text/StorageNBTComponent.java
- api/src/main/java/net/kyori/adventure/text/TextComponent.java
- api/src/main/java/net/kyori/adventure/text/TextReplacementConfig.java
- api/src/main/java/net/kyori/adventure/text/TranslatableComponent.java
- api/src/main/java/net/kyori/adventure/text/format/Style.java
- api/src/main/java/net/kyori/adventure/text/format/StyleBuilderApplicable.java
- api/src/main/java/net/kyori/adventure/util/Buildable.java
> Add JetBrains Contract annotations to some methods

- nbt/src/main/java/net/kyori/adventure/nbt/ListBinaryTag.java
> nbt: ListBinaryTag.getList

- serializer-configurate3/src/test/java/net/kyori/adventure/serializer/configurate3/ComponentSerializerTest.java
- serializer-configurate4/src/test/java/net/kyori/adventure/serializer/configurate4/ComponentSerializerTest.java
- text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/ComponentSerializerImpl.java
- text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/StyleSerializer.java
- text-serializer-gson/src/test/java/net/kyori/adventure/text/serializer/gson/GsonComponentSerializerTest.java
> serializer-gson: Change output ordering to match the order of Vanilla components

- api/src/main/java/net/kyori/adventure/text/format/TextColor.java
- api/src/test/java/net/kyori/adventure/text/format/TextColorTest.java
- text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerImpl.java
- text-serializer-legacy/src/test/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerTest.java
working on the issue backlog a bit, these are a few simple things.
> few fixes, see commits for details

- nbt/src/main/java/net/kyori/adventure/nbt/CompoundBinaryTagImpl.java
- nbt/src/main/java/net/kyori/adventure/nbt/CompoundTagBuilder.java
- nbt/src/main/java/net/kyori/adventure/nbt/CompoundTagSetter.java
> feature(nbt): allow merging compound tags via 'this.put(that)'

- text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerImpl.java
- text-serializer-legacy/src/test/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerTest.java
haven't yet made it to solving both issues yet, sadly
> text-serializer-legacy: wip on removing redundant resets while also preserving supplied resets

- .gitignore
- extra-kotlin/build.gradle
- extra-kotlin/src/main/kotlin/net/kyori/adventure/extra/kotlin/ComponentDSL.kt
- extra-kotlin/src/main/kotlin/net/kyori/adventure/extra/kotlin/ComponentExtensions.kt
- extra-kotlin/src/main/kotlin/net/kyori/adventure/extra/kotlin/RGBLikeExtensions.kt
- extra-kotlin/src/main/kotlin/net/kyori/adventure/extra/kotlin/StyleDSL.kt
- settings.gradle
> extra-kotlin

- text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerImpl.java
- text-serializer-legacy/src/test/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerTest.java
The trailing reset seems to have caused more problems than it's fixed, so let's get rid of it.
> text-serializer-legacy: tweak reset behavior AGAIN

- api/src/main/java/net/kyori/adventure/text/serializer/ComponentSerializer.java
> api: Add serializer methods that will process null values

- api/build.gradle
- bom/build.gradle
- build.gradle
- extra-kotlin/build.gradle
- key/build.gradle
- nbt/build.gradle
- serializer-configurate3/build.gradle
- serializer-configurate4/build.gradle
- text-serializer-gson-legacy-impl/build.gradle
- text-serializer-gson/build.gradle
- text-serializer-legacy/build.gradle
- text-serializer-plain/build.gradle
> build: Add extra metadata to jar manifests

- api/src/main/java/net/kyori/adventure/text/TextReplacementConfig.java
- api/src/main/java/net/kyori/adventure/text/TextReplacementConfigImpl.java
- api/src/main/java/net/kyori/adventure/text/TextReplacementRenderer.java
- api/src/test/java/net/kyori/adventure/text/TextReplacementRendererTest.java
> api: Allow passing the replacement MatchResult to continuation predicates

- api/src/main/java/net/kyori/adventure/text/serializer/ComponentSerializer.java
> Component serializer typo

- api/src/main/java/net/kyori/adventure/text/Component.java
- api/src/test/java/net/kyori/adventure/text/TextComponentTest.java
> api: Add contains method that allows alternative methods of equality comparison

- api/src/main/java/net/kyori/adventure/text/AbstractComponentBuilder.java
- api/src/main/java/net/kyori/adventure/text/ScopedComponent.java
> api: Be more strict about validating nullness of appended components

- api/src/main/java/net/kyori/adventure/bossbar/BossBar.java
- api/src/main/java/net/kyori/adventure/text/Component.java
- api/src/main/java/net/kyori/adventure/text/TextComponent.java
- api/src/main/java/net/kyori/adventure/text/serializer/ComponentSerializer.java
- api/src/main/java/net/kyori/adventure/util/ShadyPines.java
- text-serializer-plain/src/main/java/net/kyori/adventure/text/serializer/plain/PlainComponentSerializer.java
> api: Add inVersion to all @ApiStatus.ScheduledForRemoval annotations

- api/src/main/java/net/kyori/adventure/text/ComponentCompaction.java
- api/src/test/java/net/kyori/adventure/text/ComponentCompactingTest.java
Stealing @zml2008's thunder but it "appears to work for now"
(fixes #455 because github doesn't understand if i put it in the title)
> Fix #455 and add a test for it

- readme.md
Just makes the full docs a little more accessible.
> Add Java Docs to the Readme

- api/src/main/java/net/kyori/adventure/text/ScopedComponent.java
Probably a malicious auto correct
> Fix return type on #decorate method in ScopedComponent

- api/src/main/java/net/kyori/adventure/text/AbstractComponentBuilder.java
- api/src/main/java/net/kyori/adventure/text/BlockNBTComponentImpl.java
- api/src/main/java/net/kyori/adventure/text/Component.java
- api/src/main/java/net/kyori/adventure/text/ComponentLike.java
- api/src/main/java/net/kyori/adventure/text/EntityNBTComponentImpl.java
- api/src/main/java/net/kyori/adventure/text/KeybindComponentImpl.java
- api/src/main/java/net/kyori/adventure/text/NBTComponentImpl.java
- api/src/main/java/net/kyori/adventure/text/ScoreComponentImpl.java
- api/src/main/java/net/kyori/adventure/text/SelectorComponentImpl.java
- api/src/main/java/net/kyori/adventure/text/StorageNBTComponentImpl.java
- api/src/main/java/net/kyori/adventure/text/TextComponentImpl.java
- api/src/main/java/net/kyori/adventure/text/TranslatableComponentImpl.java
- api/src/main/java/net/kyori/adventure/text/format/Style.java
- api/src/main/java/net/kyori/adventure/text/format/StyleImpl.java
- api/src/main/java/net/kyori/adventure/title/TitleImpl.java
Add calls to `requireNonNull` in more places. Some values are already checked in the constructor, redundant validations have been removed.
Addresses #442
> Add more non-null value validations

- api/src/main/java/net/kyori/adventure/text/TextReplacementRenderer.java
- api/src/test/java/net/kyori/adventure/text/TextAssertions.java
- api/src/test/java/net/kyori/adventure/text/TextReplacementRendererTest.java
> api: Resolve duplication of children when performing text replacement

- text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/transformation/inbuild/GradientTransformation.java
- text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/transformation/inbuild/RainbowTransformation.java
- text-minimessage/src/test/java/net/kyori/adventure/text/minimessage/MiniMessageParserTest.java
> text-minimessage: Properly handle colour override depth reductions

- api/src/main/java/net/kyori/adventure/text/Component.java
- api/src/main/java/net/kyori/adventure/text/TextComponent.java
- api/src/test/java/net/kyori/adventure/text/TextComponentTest.java
This indirectly reverts commit 9ffba5b718bd396e6d397c6543c1982d9e631b08.
> api: Introduce Component.textOfChildren as a replacement for TextComponent.ofChildren

- api/src/main/java/net/kyori/adventure/util/HSVLikeImpl.java
- api/src/test/java/net/kyori/adventure/util/HSVLikeTest.java
> util: Add a range check for HSVLike

- text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/MiniMessageParser.java
- text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/internal/parser/TokenParser.java
- text-minimessage/src/test/java/net/kyori/adventure/text/minimessage/MiniMessageParserTest.java
Implemented the nagging feature from API to MiniMessage. But because API wasn't a part of MiniMessage I put down a small method and used that.
> Implemented #515.
