src/main/java/net/kyori/text/AbstractBuildableComponent.java
src/main/java/net/kyori/text/BuildableComponent.java

Allows you to do stuff like this.
```java
BuildableComponent someComponent = LegacyComponent.from("&cHello &bworld.", '&');
BuildableComponent.Builder<?, ?> builder = someComponent.toBuilder();
HoverEvent hoverEvent = new HoverEvent(HoverEvent.Action.SHOW_TEXT, TextComponent.of("Hi there!"));
builder.applyDeep(b -> b.hoverEvent(hoverEvent));
someComponent = builder.build();
```
In this case, take a whole component and applying a HoverEvent to everything, including all children. This is especially useful for modifying components obtained from other sources, or applying hover/click events to legacy text.
Also (perhaps) useful, is the ability to completely remap an existing component. For example, find a specific KeybindComponent, and replace it with a TextComponent.
```java
// some magic …
```

Add methods to perform modifications to child components recursively

---

src/main/java/net/kyori/text/LegacyComponent.java
src/test/java/net/kyori/text/LegacyComponentTest.java

Fixes all components inheriting color/style from the first component in the chain.
For example, currently:
```
&3> &rpms &7- &rfalse
```
is parsed to

Fix deserialization of legacy text

---

readme.md

In the first two examples are the names in the comments actually wrong.
* The first one that uses `textComponent` actually mentions `component`
* The second one that uses `textComponent2` actually mentions `textComponents`
This isn't that big of an issue, yet I still thought it worthy of a correction :)

Updating wrong example-names

---

text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer.java
text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerImpl.java
text-serializer-legacy/src/test/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerTest.java

otherwise we start trying to send RGB color codes to old versions, and that looks pretty awkward :)

serializer-legacy: Add option to downsample text colors when using legacy format

---

text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer.java
text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerImpl.java
text-serializer-legacy/src/test/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerTest.java

Pretty gross but it works I suppose.
Is needed in order to support setting things like entity / itemstack custom names to `Component`s on Bukkit.

Add support for serializing to bungeecord-chat's legacy hex format

---

nbt/src/main/java/net/kyori/adventure/nbt/impl/TagStringReader.java
nbt/src/test/java/net/kyori/adventure/nbt/impl/StringIOTest.java

This makes the old `[0:"hello",1:"hello2"]` list format readable. Since it's always written from 0 upwards (and any other sane legacy lib should do the same, and and it would require changes to the builder otherwise), I simply ignored the actual index.

Fix nbt array reading with prefixed indexes

---

api/src/main/java/net/kyori/adventure/util/Listenable.java

This class has thread-safety issues: the `listeners` field is not updated in an atomic matter, which may cause a `NullPointerException` or listeners to not be successfully added or removed when any class that extends `Listenable` is used from multiple threads. This is a problem especially for Velocity and BungeeCord as both are multi-threaded.
I decided to go with the "obvious, safe" route to solve this problem. This PR resolves the issue by:
* Switching to `CopyOnWriteArrayList` as a more appropriate data structure.
* Always initializing the `listeners` field. This appears to be an attempt at reducing memory usage, but I really don't think anyone will lose sleep over wasting 48 bytes in the worst case if there are no listeners ever registered.
We can explore other approaches if that is …

Make Listenable thread-safe

---

api/src/main/java/net/kyori/adventure/bossbar/BossBarImpl.java

Boss bars are still the same bar, even if all of the instance's fields change. equals() and hashCode() should reflect that.
This makes using boss bars as map keys more reliable.

Boss bar equality based on object identity

---

nbt/src/main/java/net/kyori/adventure/nbt/BinaryTagIO.java
nbt/src/main/java/net/kyori/adventure/nbt/IOStreamUtil.java

While looking at `adventure-nbt` I spotted two issues:
* Lack of stream buffering. This can hurt performance, especially for compressed NBT and slow disks.
* `BinaryTagIO` will indiscriminately close streams given to it. For single-shot cases or reading from a in-memory buffer this isn't an issue, but if (say) you were parsing a set of NBT streams this could be an issue.
To fix this:
* `Path`-taking methods and `*Compressed*` methods now buffer the relevant streams (I assume if you're passing in an `InputStream` or a `DataInput` directly that you know what you're doing)
* Added code so that `BinaryTagIO` won't close streams it is given
Still a bit of a WIP (need to write tests), but wanted to get this up here.

Improve performance of BinaryTagIO by buffering and clarify stream closing

---

text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerImpl.java
text-serializer-legacy/src/test/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerTest.java
text-serializer-legacy/src/test/java/net/kyori/adventure/text/serializer/legacy/LinkingLegacyComponentSerializerTest.java

Fixes #108.
This does introduce a behavioral change: we now revert to the historical text 3.x behavior of using the very first component found and append everything else as children. This change was made in #82 but it was botched and I didn't notice until now.

Fix regression in #82 with a single chat component from the main logic loop

---

api/src/main/java/net/kyori/adventure/text/TextComponent.java
api/src/main/java/net/kyori/adventure/text/TextComponentImpl.java
api/src/main/java/net/kyori/adventure/util/IntPredicate2.java
api/src/test/java/net/kyori/adventure/text/TextComponentTest.java

Add replace(n) and replaceFirst methods to TextComponent

---

api/src/main/java/net/kyori/adventure/text/event/HoverEvent.java

Just some copy-and-paste typos I found.

Fix typos in HoverEvent.ShowEntity

---

nbt/src/main/java/net/kyori/adventure/nbt/TagStringReader.java
nbt/src/test/java/net/kyori/adventure/nbt/StringIOTest.java

Previously, parsing would fail for compounds like `{}` or `{a: \"hello\", empty: {}}`

Fix empty compound parsing

---

nbt/src/main/java/net/kyori/adventure/nbt/CharBuffer.java
nbt/src/main/java/net/kyori/adventure/nbt/TagStringReader.java
nbt/src/test/java/net/kyori/adventure/nbt/StringIOTest.java

follow-up to #131 to apply the same logic to other tag types

nbt: Corrently handle other empty tag types

---

text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/GsonComponentSerializer.java
text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/GsonComponentSerializerImpl.java

Just a bug I noticed while working on something unrelated.

text-serializer-gson: Ensure GsonComponentSerializer#toBuilder() carries over legacy hover event serializer configuration

---

api/src/main/java/net/kyori/adventure/text/AbstractComponent.java
api/src/main/java/net/kyori/adventure/text/Component.java
api/src/main/java/net/kyori/adventure/text/PatternReplacementResult.java
api/src/main/java/net/kyori/adventure/text/TextComponent.java
api/src/main/java/net/kyori/adventure/text/TextComponentImpl.java
api/src/main/java/net/kyori/adventure/text/TextReplacementRenderer.java
api/src/main/java/net/kyori/adventure/text/event/HoverEvent.java
api/src/main/java/net/kyori/adventure/text/renderer/ComponentRenderer.java
api/src/test/java/net/kyori/adventure/text/TextComponentTest.java
text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer.java
text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerImpl.java
text-serializer-legacy/src/test/java/net/kyori/adventure/text/serializer/legacy/LinkingLegacyComponentSerializerTest.java

This now properly handles non-`TextComponent` children, plus traverses `TranslatableComponent`s and hover events.
At some point the logic in this and in `TranslatableComponentRenderer` should be abstracted out into a common component visitor. There's also potential to expand the exposed replacement api -- this PR doesn't expose any new functionality.

Revise text component replacement

---

api/src/main/java/net/kyori/adventure/text/TranslatableComponentImpl.java

This is accepted by vanilla for some reason, although it's not particularly logical. See https://gist.github.com/astei/7a5ed3afedf6e4b23dcb99e0d72ea315

api: Allow TranslatableComponent builder to use empty keys

---

api/src/main/java/net/kyori/adventure/text/renderer/TranslatableComponentRenderer.java

Fixes some omissions in merging when rendering components.
@kashike mentioned there was some reason behind not just setting the style and overriding the hover event but couldn't remember what, so we are just expanding the merge instead.

renderer: Fix merging of fonts and insertions

---

.gitignore
serializer-configurate3/build.gradle
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/BlockNBTPosSerializer.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/BookTypeSerializer.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/ComponentTypeSerializer.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/ConfigurateComponentSerializer.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/ConfigurateComponentSerializerImpl.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/DurationSerializer.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/HoverEventShowEntitySerializer.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/HoverEventShowItemSerializer.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/IndexSerializer.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/KeySerializer.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/SoundSerializer.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/SoundStopSerializer.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/StyleSerializer.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/TextColorSerializer.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/TitleSerializer.java
serializer-configurate3/src/test/java/net/kyori/adventure/serializer/configurate3/BookSerializerTest.java
serializer-configurate3/src/test/java/net/kyori/adventure/serializer/configurate3/ComponentSerializerTest.java
serializer-configurate3/src/test/java/net/kyori/adventure/serializer/configurate3/ConfigurateTestBase.java
serializer-configurate3/src/test/java/net/kyori/adventure/serializer/configurate3/HoverEventSerializersTest.java
serializer-configurate3/src/test/java/net/kyori/adventure/serializer/configurate3/ScalarSerializersTest.java
serializer-configurate3/src/test/java/net/kyori/adventure/serializer/configurate3/SoundSerializersTest.java
serializer-configurate3/src/test/java/net/kyori/adventure/serializer/configurate3/StyleSerializerTest.java
serializer-configurate3/src/test/java/net/kyori/adventure/serializer/configurate3/TitleSerializerTest.java
settings.gradle

This allows for better integration with configurate-using projects (at least those with Configurate 3.7).
Unlike the other serializers, the main purpose of this serializer is for working with configuration files, so it supports serializing more types than just `Component`s.

Configurate serializer

---

api/src/main/java/net/kyori/adventure/text/Component.java

Example usage:
---
Before:
```java
Component message = Component.text("Your nickname is now {}.", NamedTextColor.YELLOW)
.replaceFirstText(Pattern.compile("{}", Pattern.LITERAL), old -> Component.text(nickname, NamedTextColor.GREEN).toBuilder());
```
After:
```java
Component message = Component.text("Your nickname is now {}.", NamedTextColor.YELLOW)
.replaceFirstText("{}", Component.text(nickname, NamedTextColor.GREEN));
```

Add Non-Regex, Non-Lambda overloads for replace methods

---

api/src/main/java/net/kyori/adventure/audience/Audience.java
api/src/main/java/net/kyori/adventure/audience/Audiences.java
api/src/test/java/net/kyori/adventure/audience/AudienceTest.java

This arose out of somewhat related discussion that led to #155 being filed, but it's not related.
This API adds a collector for `Audience`s. It is a convenient and idiomatic shorthand for `Audience.of(stream.collect(Collectors.toList()))` and is more concise: `stream.collect(Audience.toAudience())`

api: Add Audience.toAudience()

---

api/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties
nbt/build.gradle
serializer-configurate4/build.gradle

Uses the new `compileOnlyApi` configuration.
I've not set things up to use toolchains yet -- adding version-specific test tasks is a bit annoying, will probably wait to finish the pull multirelease jar plugin for that.

build: Update for gradle 6.7

---

text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/ShowItemSerializer.java

This fixes an error being thrown when trying to deserialise (from json) an item hover with a null nbt tag as seen in the example below.
```json
{"translate":"commands.give.success.single","with":["1",{"translate":"chat.square_brackets","with":[{"text":"","extra":[{"translate":"block.minecraft.stone"}]}],"color":"white","hoverEvent":{"action":"show_item","contents":{"id":"minecraft:stone","count":0,"tag":null}}},{"text":"rtm516","clickEvent":{"action":"suggest_command","value":"/tell rtm516 "},"hoverEvent":{"action":"show_entity","contents":{"type":"minecraft:player","id":"cb7a4c0c-a7cd-4846-8b6f-477de8f5f3ee","name":"rtm516"}},"insertion":"rtm516"}]}
```
with `{"id":"minecraft:stone","count":0,"tag":null}` being the main issue

Add a check for null nbt data on item hovers

---

nbt/src/main/java/net/kyori/adventure/nbt/ArrayBinaryTag.java
nbt/src/main/java/net/kyori/adventure/nbt/ArrayBinaryTagImpl.java
nbt/src/main/java/net/kyori/adventure/nbt/ByteArrayBinaryTagImpl.java
nbt/src/main/java/net/kyori/adventure/nbt/IntArrayBinaryTag.java
nbt/src/main/java/net/kyori/adventure/nbt/IntArrayBinaryTagImpl.java
nbt/src/main/java/net/kyori/adventure/nbt/ListBinaryTag.java
nbt/src/main/java/net/kyori/adventure/nbt/ListBinaryTagImpl.java
nbt/src/main/java/net/kyori/adventure/nbt/LongArrayBinaryTag.java
nbt/src/main/java/net/kyori/adventure/nbt/LongArrayBinaryTagImpl.java

This allows interacting with array tags without creating a copy of the
backing array.
Not sure how to handle the primitive consumer `forEach` methods -- they're currently ambiguous with the boxed variants from the `Iterable` interface.

nbt: Add array access and stream methods for tags

---

api/src/main/java/net/kyori/adventure/text/AbstractComponent.java
api/src/main/java/net/kyori/adventure/text/Component.java
api/src/main/java/net/kyori/adventure/text/TextReplacementConfig.java
api/src/main/java/net/kyori/adventure/text/TextReplacementConfigImpl.java
api/src/test/java/net/kyori/adventure/text/TextComponentTest.java
text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerImpl.java

This allows accessing the MatchResult directly when doing a replacement.

api: Add a builder for replacement config

---

.checkstyle/checkstyle.xml
api/src/main/java/net/kyori/adventure/identity/Identities.java
api/src/main/java/net/kyori/adventure/text/Component.java
api/src/main/java/net/kyori/adventure/text/PatternReplacementResult.java
api/src/main/java/net/kyori/adventure/text/TextReplacementConfig.java
api/src/main/java/net/kyori/adventure/text/TextReplacementConfigImpl.java
api/src/main/java/net/kyori/adventure/text/renderer/TranslatableComponentRenderer.java
api/src/main/java/net/kyori/adventure/util/Index.java
api/src/test/java/net/kyori/adventure/text/TextComponentTest.java
nbt/src/main/java/net/kyori/adventure/nbt/CompoundBinaryTagImpl.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/ComponentTypeSerializer.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/ConfigurateComponentSerializerImpl.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/HoverEventShowEntitySerializer.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/StyleSerializer.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/TitleSerializer.java
serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/ComponentTypeSerializer.java
serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/ConfigurateComponentSerializerImpl.java
serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/HoverEventShowEntitySerializer.java
serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/StyleSerializer.java
serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/TitleSerializer.java
text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/ComponentSerializerImpl.java
text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/ShowEntitySerializer.java
text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/ShowItemSerializer.java
text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/StyleSerializer.java
text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/TextColorSerializer.java

Now that we build using javac 11, we can use LVT type use annotations again -- so uncommenting those is the biggest change. Some other type inference things that javac 8 couldn't handle are added too.
This brings over a few whitespace checks from the checkstyling of MiniMessage as well -- though those didn't result in any actual code changes here.

Some tidying and checkstyle revisions

---

.checkstyle/checkstyle.xml
api/src/main/java/net/kyori/adventure/bossbar/BossBar.java
api/src/main/java/net/kyori/adventure/identity/Identity.java
api/src/main/java/net/kyori/adventure/inventory/Book.java
api/src/main/java/net/kyori/adventure/key/Key.java
api/src/main/java/net/kyori/adventure/package-info.java
api/src/main/java/net/kyori/adventure/sound/Sound.java
api/src/main/java/net/kyori/adventure/sound/SoundStop.java
api/src/main/java/net/kyori/adventure/text/BlockNBTComponent.java
api/src/main/java/net/kyori/adventure/text/Component.java
api/src/main/java/net/kyori/adventure/text/EntityNBTComponent.java
api/src/main/java/net/kyori/adventure/text/KeybindComponent.java
api/src/main/java/net/kyori/adventure/text/LinearComponents.java
api/src/main/java/net/kyori/adventure/text/NBTComponent.java
api/src/main/java/net/kyori/adventure/text/ScoreComponent.java
api/src/main/java/net/kyori/adventure/text/SelectorComponent.java
api/src/main/java/net/kyori/adventure/text/StorageNBTComponent.java
api/src/main/java/net/kyori/adventure/text/TextComponent.java
api/src/main/java/net/kyori/adventure/text/TranslatableComponent.java
api/src/main/java/net/kyori/adventure/text/event/ClickEvent.java
api/src/main/java/net/kyori/adventure/text/format/Style.java
api/src/main/java/net/kyori/adventure/text/format/TextColor.java
api/src/main/java/net/kyori/adventure/title/Title.java
api/src/main/java/net/kyori/adventure/translation/GlobalTranslator.java
api/src/main/java/net/kyori/adventure/translation/TranslationRegistry.java
api/src/main/java/net/kyori/adventure/translation/Translator.java
build.gradle

Saw #226 and typed out a draft for a possible javadocs expansion, feedback appreciated.

Expand javadocs

---

serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/ComponentTypeSerializer.java
serializer-configurate3/src/test/java/net/kyori/adventure/serializer/configurate3/ComponentSerializerTest.java
serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/ComponentTypeSerializer.java
serializer-configurate4/src/test/java/net/kyori/adventure/serializer/configurate4/ComponentSerializerTest.java

Without this change, the `preferString` flag would be effectively ignored.

serializer-configurate*: Fix handling of string component output

---

api/src/main/java/net/kyori/adventure/text/AbstractComponent.java
api/src/main/java/net/kyori/adventure/text/TranslatableComponentImpl.java
api/src/test/java/net/kyori/adventure/text/TranslatableComponentTest.java

Consider the following scenario: 
```java
MessageFormat format = new MessageFormat("{1} was killed by {2}"); // key = player.death
Component message = translatable()
.key("player.death")
.args(empty(), text("Bob"), text("Alice"))
.build()
```
If you translate `message` today, you'll get `"Alice was killed by {2}"`. This is because `AbstractComponent#asComponents` filters out `Component#empty`. While this works in most situations, it causes index-skew with `TranslatableComponent`.

Include empty components in translatable arguments

---

key/src/main/java/net/kyori/adventure/key/Key.java
key/src/main/java/net/kyori/adventure/key/Namespaced.java

Allows something like a `Plugin` to implement `Namespaced`, and then do:
```java
final Plugin plugin = ...;
final Key key = Key.key(plugin, "foo");
```

key: Namespaced

---

text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerImpl.java
text-serializer-legacy/src/test/java/net/kyori/adventure/text/serializer/legacy/LinkingLegacyComponentSerializerTest.java

Fixes a bug where legacy text containing URLs without protocol specification would cause a crash on old minecraft versions.
Modern minecraft versions just refuse to open the URL dialog without this.

text-serializer-legacy: Vanilla implementation for URL conversion

---

api/src/main/java/net/kyori/adventure/text/format/NamedTextColor.java
api/src/main/java/net/kyori/adventure/util/HSVLike.java
api/src/main/java/net/kyori/adventure/util/HSVLikeImpl.java
api/src/main/java/net/kyori/adventure/util/RGBLike.java
api/src/test/java/net/kyori/adventure/text/format/NamedTextColorTest.java
api/src/test/java/net/kyori/adventure/util/HSVLikeTest.java
api/src/test/java/net/kyori/adventure/util/RGBLikeTest.java

The code for RGB to HSV conversion is based on the example code [here](https://www.cs.rit.edu/~ncs/color/t_convert.html), modified to behave more like java.awt.Color.RGBtoHSB.
In my limited testing, this algorithm for color distance seems to match gray less often, leading to a more "correct" result for color down sampling.
comparison:
original:
old downsample:
new downsample:

api: Add asHSV to RGBLike and use HSV for color comparisons in NamedTextColor.nearestTo

---

nbt/src/main/java/net/kyori/adventure/nbt/BinaryTagIO.java
nbt/src/test/java/net/kyori/adventure/nbt/BinaryTagIOTest.java

Added support for ZLIB using `InflatedInputStream` and `DeflatedOutputStream` to compress and decompress respectively. Has been tested.

Added ZLIB compression support for NBT

---

api/src/main/java/net/kyori/adventure/text/format/TextColor.java
api/src/test/java/net/kyori/adventure/util/HSVLikeTest.java

Adapted from the same [example](https://www.cs.rit.edu/~ncs/color/t_convert.html) as in #280

api: Add a method to create a TextColor from an HSVLike

---

api/src/main/java/net/kyori/adventure/text/AbstractComponentBuilder.java
api/src/main/java/net/kyori/adventure/text/Component.java
api/src/main/java/net/kyori/adventure/text/ComponentBuilder.java
api/src/test/java/net/kyori/adventure/text/AbstractComponentTest.java

api: Add methods to join components using a collector

---

api/src/main/java/net/kyori/adventure/text/AbstractComponent.java
api/src/main/java/net/kyori/adventure/text/BlockNBTComponentImpl.java
api/src/main/java/net/kyori/adventure/text/EntityNBTComponentImpl.java
api/src/main/java/net/kyori/adventure/text/KeybindComponentImpl.java
api/src/main/java/net/kyori/adventure/text/NBTComponentImpl.java
api/src/main/java/net/kyori/adventure/text/ScoreComponentImpl.java
api/src/main/java/net/kyori/adventure/text/SelectorComponentImpl.java
api/src/main/java/net/kyori/adventure/text/StorageNBTComponentImpl.java
api/src/main/java/net/kyori/adventure/text/TextComponentImpl.java
api/src/main/java/net/kyori/adventure/text/TranslatableComponentImpl.java
api/src/main/java/net/kyori/adventure/text/format/TextColorImpl.java
nbt/build.gradle
nbt/src/main/java/net/kyori/adventure/nbt/ByteArrayBinaryTagImpl.java
nbt/src/main/java/net/kyori/adventure/nbt/ByteBinaryTag.java
nbt/src/main/java/net/kyori/adventure/nbt/CompoundBinaryTagImpl.java
nbt/src/main/java/net/kyori/adventure/nbt/DoubleBinaryTag.java
nbt/src/main/java/net/kyori/adventure/nbt/FloatBinaryTag.java
nbt/src/main/java/net/kyori/adventure/nbt/IntArrayBinaryTagImpl.java
nbt/src/main/java/net/kyori/adventure/nbt/IntBinaryTag.java
nbt/src/main/java/net/kyori/adventure/nbt/ListBinaryTagImpl.java
nbt/src/main/java/net/kyori/adventure/nbt/LongArrayBinaryTagImpl.java
nbt/src/main/java/net/kyori/adventure/nbt/LongBinaryTag.java
nbt/src/main/java/net/kyori/adventure/nbt/ShortBinaryTag.java
nbt/src/main/java/net/kyori/adventure/nbt/StringBinaryTag.java

This adds some extra annotations to our main hierarchical data structures -- `Component`s and NBT that give a more streamlined view of objects in the debugger.
**Before:** 
**After:**
(the implementation of this is a bit ugly at the moment -- perhaps there's space to improve it with changes to `examination`?)
**Before:** 
**After:**:

Customize Debugger Output

---

api/src/main/java/net/kyori/adventure/text/Component.java
api/src/main/java/net/kyori/adventure/text/ScoreComponent.java
api/src/main/java/net/kyori/adventure/text/ScoreComponentImpl.java
api/src/main/java/net/kyori/adventure/text/renderer/TranslatableComponentRenderer.java
api/src/test/java/net/kyori/adventure/text/ScoreComponentTest.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/ComponentTypeSerializer.java
serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/ComponentTypeSerializer.java
text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/ComponentSerializerImpl.java
text-serializer-plain/src/main/java/net/kyori/adventure/text/serializer/plain/PlainComponentSerializer.java

Mojang removed this field from 1.16, so it will be ignored when used there.

api: Mark ScoreComponent's value as deprecated since it is no longer supported

---

api/src/main/java/net/kyori/adventure/translation/TranslationRegistry.java
api/src/main/java/net/kyori/adventure/translation/TranslationRegistryImpl.java

Adds a method to check if a translation key has any registered translations.
This allows one to easily handle a missing translation key using a custom fallback.

API addition for translations

---

text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/GsonComponentSerializer.java
text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/GsonComponentSerializerImpl.java

This PR adds three new `deserialize` methods in `GsonComponentSerializer` and the respective implementation that enable the deserialisation of `JsonReader`, `JsonElement` and `Reader` objects.
I'm not sure if this was the best way to add them as they won't be accessible using the `ComponentSerializer` interface. I suppose each new deserialisation method could be put in it's own `ComponentSerializer` but it feels best suited to the `GsonComponentSerializer`.
I also haven't introduced any tests yet. I was not sure what the best way to go about introducing tests would be. Perhaps a separate class or mutating the existing ones to test against all the deserialisers? I'd appreciate some pointers!
Merging this PR will close #293.

serializer-gson: Add deserializers for JsonElement, Reader and JsonReader

---

api/src/main/java/net/kyori/adventure/bossbar/BossBar.java
api/src/main/java/net/kyori/adventure/text/Component.java

This PR annotates all deprecated methods which are currently manually marked as "for removal" with the `ScheduledForRemoval` annotation.

Annotate more deprecated methods with `ScheduledForRemoval`

---

key/src/main/java/net/kyori/adventure/key/Key.java

This PR improves the javadocs for two of the static `key` methods that "parse" the input into a key.

key: Improve key method javadocs

---

api/src/main/java/net/kyori/adventure/text/Component.java
api/src/test/java/net/kyori/adventure/text/ComponentContainsTest.java
api/src/test/java/net/kyori/adventure/text/TextComponentTest.java

This PR modifies `Component#contains(Component)` to check for the name of an entity in a `ShowEntity` hover event and adds some tests.

api: Make contains check for entity name

---

api/src/main/java/net/kyori/adventure/audience/ForwardingAudience.java

Hello! I may be misunderstanding this interface, but I believe Single should be inheriting the `Pointered` methods from its `audience()`, rather than its super class.
Basically, `Single#getOrDefault` is currently inherited from ForwardingAudience which always returns the default rather than redirecting the query to `this.audience()`. This fixes that.

api: Add Pointer query to Single

---

api/src/main/java/net/kyori/adventure/text/Component.java
api/src/main/java/net/kyori/adventure/text/TranslatableComponent.java
api/src/main/java/net/kyori/adventure/translation/Translatable.java

This PR adds a `Translatable` interface with the intention of allowing implementations to implement this interface on objects which can be translated.

api: Add Translatable interface

---

build-logic/src/main/kotlin/adventure.common-conventions.gradle.kts

This doesn't verify that the contracts say the right thing, but it does ensure that they are well-formed and applicable to the method's argument types.
See https://github.com/zml2008/contract-validator for the project used

build: Apply contract-validator to ensure contract annotations are syntactically valid

---

api/src/main/java/net/kyori/adventure/audience/Audience.java
api/src/main/java/net/kyori/adventure/audience/ForwardingAudience.java
api/src/main/java/net/kyori/adventure/sound/Sound.java
api/src/main/java/net/kyori/adventure/sound/SoundImpl.java

This is a simple PR that adds the concept of a sound "player". The interface for `Sound.Player` is intentionally empty, as the way the client/server identifies a sound player is with the entity ID, an implementation detail that some platforms may not wish to expose. 
The general idea is that a native implementation will implement `Sound.Player` on their entity class, allowing it to be passed directly as an argument into the `playSound` method. For platforms, they could provide utility methods to convert their entity class to an implementation of the `Sound.Player` interface which provides an entity object, or some other form of identifier. This can then be used to convert to the platform specific way of sending the entity sound effect packet.
Alternatively, the `Sound.Player` could …

api: Add support for playing sound with an "emitter"

---

api/src/main/java/net/kyori/adventure/pointer/Pointered.java
api/src/main/java/net/kyori/adventure/pointer/Pointers.java
api/src/main/java/net/kyori/adventure/pointer/PointersImpl.java
api/src/test/java/net/kyori/adventure/pointer/PointersTest.java

This PR adds a class that holds a collection of pointers and optional values. With this class, the following goals are achieved:
With a class such as this, implementing the pointered interface will only involve building a pointers instance and returning it. 
```java
@Override
@SuppressWarnings("unchecked") // safe casts
public @NonNull <T> Optional<T> get(@NonNull Pointer<T> pointer) {
if(pointer.equals(NAME)) return Optional.ofNullable((T) this.name());
if(pointer.equals(SERVER_NAME)) return Optional.of(this.getServer().name());
return Optional.empty();
}
```
```java
private Pointers pointers = null;
@Override
public @NonNull Pointers pointers() {
if(this.pointers == null) {
this.pointers = Pointers.builder()
.addPointerWithVariableValue(NAME, this::name) …
```

api: Add Pointers

---

build-logic/src/main/kotlin/CopyJavadoc.kt
build-logic/src/main/kotlin/JavadocPackaging.kt
build-logic/src/main/kotlin/adventure.common-conventions.gradle.kts
gradle.properties

This automates one of the release steps.
I've also set up JD linking so we can cross-link between projects. The links will point to the final locations at `https://jd.adventure.kyori.net`, but this URL is a gradle property that can be overridden to point to other publishing locations.
When releasing, run `./gradlew copyJavadoc --output ../adventure-javadocs` to copy JD to the appropriate location.

Make Gradle automatically copy JD to the appropriate location for JD repo

---

api/src/main/java/net/kyori/adventure/audience/ForwardingAudience.java

This matches the rest of the `Pointered` methods, and appears to be an omission.

api: Make sure pointers() is overridden in ForwardingAudience.Single

---

.checkstyle/suppressions.xml
api/build.gradle.kts
api/src/jmh/java/net/kyori/adventure/text/ComponentCompactionBenchmark.java
api/src/main/java/net/kyori/adventure/text/AbstractComponent.java
api/src/main/java/net/kyori/adventure/text/Component.java
api/src/main/java/net/kyori/adventure/text/ComponentCompaction.java
api/src/main/java/net/kyori/adventure/text/format/StyleImpl.java
api/src/test/java/net/kyori/adventure/text/ComponentCompactingTest.java
build-logic/build.gradle.kts
build-logic/src/main/kotlin/adventure.common-conventions.gradle.kts
gradle.properties

Closes GH-114
This ports the implementation of component compacting over from the original Kotlin provided by @CrushedPixel (see that [here](https://paste.gg/p/zml/89fb51d013064ad6b6bb279c7486d378)) 
While this component optimization is expensive enough that it shouldn't be used on every message sent, it can be useful for ensuring components of unknown origin (such as loaded from a configuration, or built from multiple sources) are as compact as possible before being sent to users.
Some things to discuss:
- The name: Does `compact` make sense, or should we use something else like `optimize` or `pack`?
- Should a setting be added to the serializers (mainly the Configurate serializer, but possibly others) to auto-compact when loading?

api: Add support for 'compacting' components

---

api/src/main/java/net/kyori/adventure/text/TextReplacementRenderer.java
api/src/test/java/net/kyori/adventure/text/TextReplacementRendererTest.java

This PR fixes #387.
When a full match has been found, the replacement is collected and then the style of the original match is merged into this style using the `IF_ABSENT_ON_TARGET` strategy. This will replicate the behaviour of when a partial match is found as the style will inherit from the parent.

api: Merge style of full match when replaced

---

api/src/main/java/net/kyori/adventure/text/Component.java
api/src/main/java/net/kyori/adventure/text/KeybindComponent.java

Similar to the `Translatable` interface, this PR adds a `Keybind` interface for implementations with enums/whatever that represent keybinds.

api: Add Keybind interface

---

api/src/main/java/net/kyori/adventure/audience/Audience.java
api/src/main/java/net/kyori/adventure/audience/ForwardingAudience.java
api/src/main/java/net/kyori/adventure/title/Title.java
api/src/main/java/net/kyori/adventure/title/TitleImpl.java
api/src/main/java/net/kyori/adventure/title/TitlePart.java

This PR is an alternative to #320. With this PR, you would send individual title parts like:
```java
audience.showTitlePart(TitlePart.TITLE, text("hello!"));
audience.showTitlePart(TitlePart.TIMES, times(0, 100, 15));
```

api: Add TitlePart

---

api/src/main/java/net/kyori/adventure/text/Component.java
api/src/main/java/net/kyori/adventure/text/ComponentIterator.java
api/src/main/java/net/kyori/adventure/text/ComponentIteratorFlag.java
api/src/main/java/net/kyori/adventure/text/ComponentIteratorType.java
api/src/main/java/net/kyori/adventure/util/DelegatingIterable.java
api/src/main/java/net/kyori/adventure/util/ForwardingIterator.java
api/src/test/java/net/kyori/adventure/text/ComponentIteratorTest.java

Following the discussion in https://github.com/KyoriPowered/adventure/pull/310#discussion_r599837951, this PR makes the `Component` class implement `Iterable<Component>`, allowing developers to iterate through a component and their children recursively. As component are immutable, the iterator does not support removal and it will throw an exception as per the definition of the class where removal isn't supported.
There are two types of iterator included, a depth first and a breadth first one. As the breadth first iterator is slightly more performant, this is the iterator type that is returned by the implementation of the `Iterable` class in the `Component` class. The other iterator can be obtained from `ComponentIterator.iterator(component, ComponentIterator.Type.DEPTH_FIRST)`. …

api: Component iterator

---

api/src/main/java/net/kyori/adventure/audience/ForwardingAudience.java

This allows for easier overriding of these methods for forwarding
audiences that have their own pointers/identity.
(needed to implement pointers on things like the `-platform` console)

api: Don't override Pointered methods that just delegate

---

nbt/src/main/java/net/kyori/adventure/nbt/TagStringReader.java
nbt/src/test/java/net/kyori/adventure/nbt/StringIOTest.java

Legacy and modern Vanilla can parse the following SNBT with a trailing comma in compound tags, list tags, and any kind of array tag, which adventure currently cannot:
`{test: \"hello\",}`
`[I;1,2,3,]`
`[\"hello\",]`

Fix reading of trailing comma in nbt list/array/compound

---

api/src/main/java/net/kyori/adventure/title/Title.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/TitleSerializer.java
serializer-configurate3/src/test/java/net/kyori/adventure/serializer/configurate3/TitleSerializerTest.java
serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/TitleSerializer.java
serializer-configurate4/src/test/java/net/kyori/adventure/serializer/configurate4/TitleSerializerTest.java

api: Rename Title.Times.of

---

nbt/src/main/java/net/kyori/adventure/nbt/TagStringReader.java

Even though parsed as ints below as a default in its entirety, that does not account for explicitly suffixed int tags like `{id:[i;1i,2i]}` (whereas `{id:[L;1L,2L]}` works)

Fix reading of explicit int array entries

---

api/src/main/java/net/kyori/adventure/text/ComponentCompaction.java
api/src/test/java/net/kyori/adventure/text/ComponentCompactingTest.java

*Fixes KyoriPowered/adventure-text-minimessage#181*
Text joining during compaction may remove some child components.
The compaction of the component added in the unit test would return:  `2-end`
```java
final Component incorrectlyCompacted = text().append(
text('2', NamedTextColor.AQUA),
text('-'),
text().append(
text('3', NamedTextColor.BLUE),
text('4', NamedTextColor.DARK_BLUE)
),
text("end")
).build();
// Would be compacted without this fix into:
final Component compactionResult = text().append(
text('2', NamedTextColor.AQUA),
text("-end")
).build();
```

Fix joining text components with children

---

nbt/src/main/java/net/kyori/adventure/nbt/TagStringReader.java
nbt/src/test/java/net/kyori/adventure/nbt/StringIOTest.java

More cursed snbt parity issues by yours truly. `NaNd` is parsed as a double with adventure, but as a String by all Vanilla versions, same for the float equivalent. I didn't test the following statement, but as far as I can tell `Infinityd` happens to get caught by a NFE with the first f in the word already, but I figured an extra test case wouldn't hurt.

Fix accidental float and double NaN parsing

---

nbt/src/main/java/net/kyori/adventure/nbt/TagStringReader.java
nbt/src/test/java/net/kyori/adventure/nbt/StringIOTest.java

┬┴┬┴┤(･_├┬┴┬┴
If a numeric token is found before an unquoted string's end, it will be prematurely parsed as a number and errors because of remaining/unread characters for strings such as `0dd`, `11fa`, or `1350diamonds_plz`.
Instead of constantly looking for the numeric tokens, this just reads the full string and if all chars meet the required criterea (previously `possiblyNumeric`) ***except*** for the very last character, the token parser will be called. If it's possibly numeric all the way through, it goes to the int parser, otherwise to the same code below.

Fix premature SNBT parsing as number

---

api/src/main/java/net/kyori/adventure/text/TranslatableComponent.java

This critical mistake in the example usage of a TranslatedComponent obviously made the example entirely unreadable since the dot magically disappeared. Without this fix, adventure is literally unusable.
(in case it wasn't obvious: /s)

docs: Add missing dot in TranslatableComponent example

---

api/src/main/java/net/kyori/adventure/text/format/TextDecoration.java
api/src/test/java/net/kyori/adventure/text/format/TextDecorationTest.java

Felt like a naturally missing piece

Add Tristate method to TextDecoration.State

---

api/src/main/java/net/kyori/adventure/text/JoinConfiguration.java
api/src/main/java/net/kyori/adventure/text/JoinConfigurationImpl.java
api/src/test/java/net/kyori/adventure/text/JoinTest.java

While using join configurations is already rather simple, they tend to
clutter up already rather verbose source code. While the initial
creation of the JoinConfiguration already included a null configuration,
accessible through 'JoinConfiguration#noSeparators', other standards or
often used layouts were not added.
This commit adds three more defaults/standards to the join configuration
implementation that are exposed through static accessors in the join
configuration interface.
Specifically:
newLines:
A straight forward instance of the join configuraiton that uses the
new line component to join together components.
commas:
Another straight forward instance of the join configuration that uses
a single comma to join together components, creating a CSV like
layout.
arrayLike:
A more complex …

Add standard join configurations

---

text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/Context.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/ContextImpl.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/MiniMessageImpl.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/MiniMessageParser.java

Can more of these methods be removed? The only truly essential one is imo `parse(String)`, but I'm not sure what sort of usecases others might have

text-minimessage: Reduce the API surface of the parse context a little bit

---

api/src/main/java/net/kyori/adventure/text/format/TextDecoration.java
api/src/main/java/net/kyori/adventure/text/format/TextDecorationAndStateImpl.java
api/src/test/java/net/kyori/adventure/text/format/StyleTest.java
api/src/test/java/net/kyori/adventure/text/format/TextDecorationTest.java

Fixes #431. While we're at it, I noticed there was no null check for the state in the `TextDecorationAndStateImpl` constructor so I fixed that too.

api: add TextDecoration#withState and add missing null pointer check

---

api/src/main/java/net/kyori/adventure/audience/Audience.java

Clarify Audience#filterAudience(Predicate) docs

---

extra-kotlin/src/main/kotlin/net/kyori/adventure/extra/kotlin/JoinConfigurationDSL.kt

Closes #467.
Note that the redundant visibility modifiers and return types are included based on the upcoming introduction of explicit API mode.

extra-kotlin: Add some `JoinConfiguration` related methods

---

text-minimessage/src/jmh/java/net/kyori/adventure/text/minimessage/benchmark/MiniMessageBenchmark.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/MiniMessageParser.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/parser/TokenParser.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/parser/match/StringResolvingMatchedTokenConsumer.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/placeholder/DynamicPlaceholderResolver.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/placeholder/EmptyPlaceholderResolver.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/placeholder/GroupedPlaceholderResolver.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/placeholder/MapPlaceholderResolver.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/placeholder/Placeholder.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/placeholder/PlaceholderImpl.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/placeholder/PlaceholderResolver.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/placeholder/Replacement.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/placeholder/ReplacementImpl.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/transformation/TransformationRegistryImpl.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/transformation/inbuild/ComponentTransformation.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/transformation/inbuild/GradientTransformation.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/transformation/inbuild/RainbowTransformation.java
text-minimessage/src/test/java/net/kyori/adventure/text/minimessage/MiniMessageParserTest.java
text-minimessage/src/test/java/net/kyori/adventure/text/minimessage/MiniMessageTest.java
text-minimessage/src/test/java/net/kyori/adventure/text/minimessage/PlaceholderTest.java
text-minimessage/src/test/java/net/kyori/adventure/text/minimessage/TestBase.java

This PR provides a cleanup of the placeholder system and closes #518 and closes #517.
The following changes are made:
- Remove the hacky placeholder resolver methods in favour of forcing people to not use weird hacky methods.
- Swap placeholder resolvers to return a new class, `Replacement` instead, thus removing the need for a key.
- Change the map placeholder resolver constructor to use this new replacement class.
- Remove the `LazyComponentPlaceholder` as it is no longer needed due to the resolver system being lazy, if desired.
- Remove `PlaceholderResolver#canResolve` to allow easier implementation of `PlaceholderResolver` due to it being a functional interface.
Essentially, this is a move to a placeholder system that is safe at compile time. This means that (unless you ignore …

feature: Placeholder cleanup

---

api/src/main/java/net/kyori/adventure/title/TitleImpl.java
api/src/test/java/net/kyori/adventure/text/title/TitleTest.java
api/src/test/java/net/kyori/adventure/text/title/TitleTimesTest.java
api/src/test/java/net/kyori/test/EqualityAssertions.java

Adresses: #394
Also:
- Adds an util method for testing #equals and #hashcode
- Adds `requireNonNull(part)` to the title part method in `TitleImpl`

Add tests for Title and Title.Times

---

api/src/main/java/net/kyori/adventure/text/TextReplacementRenderer.java
api/src/test/java/net/kyori/adventure/text/TextReplacementRendererTest.java

Fixes #638
This matters if the component is entirely replaced due to an exact match (whereas a non-exact match creates an empty parent with no style)
I'm not 100% sure this won't cause more issues in the future, but i tried to follow how children are implemented with oldChildren

api: Use initial style when replacement-rendering a hover event

---

text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/placeholder/Placeholder.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/placeholder/Replacement.java

Moreso meant to start conversation, because I bet there's a better stage at which to escape, using the specific MiniMessage object and not just the default one. 
Presently, only a minimessage-parsed string replacement is offered. Manually doing escapeTokens all the time gets tiring, so I hope to introduce a built-into-adventure method by which to do this. Otherwise, I'll just be creating my own simple helper method to automate.
To quote @kezz 
> maybe we can do a pass right at the end once all the tokens are made

Introduce a method by which to create raw replacements.

---

text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/placeholder/PlaceholderResolver.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/placeholder/PlaceholderResolverBuilderImpl.java
text-minimessage/src/test/java/net/kyori/adventure/text/minimessage/PlaceholderResolverTest.java

Closes GH-656
Should we keep the static factory methods after this builder is added? do some of them make sense to get rid of?
I've noticed some of the static factory methods use live views of provided collections in the returned resolvers. I think this is generally the wrong choice, since it could result in live state being modified in unexpected ways, and it is trivial to implement a live `PlaceholderResolver` if that behavior truly desired. Does anyone have a defense of that live collection behavior?

text-minimessage: Add a builder for PlaceholderResolvers

---

api/src/main/java/net/kyori/adventure/nbt/api/BinaryTagHolder.java
api/src/main/java/net/kyori/adventure/text/BlockNBTComponent.java
api/src/main/java/net/kyori/adventure/text/Component.java
api/src/main/java/net/kyori/adventure/text/ComponentBuilder.java
api/src/main/java/net/kyori/adventure/text/format/NamedTextColor.java
api/src/main/java/net/kyori/adventure/text/format/Style.java
api/src/main/java/net/kyori/adventure/text/format/TextColor.java
api/src/main/java/net/kyori/adventure/text/renderer/TranslatableComponentRenderer.java
api/src/main/java/net/kyori/adventure/translation/GlobalTranslator.java
api/src/main/java/net/kyori/adventure/util/Codec.java
api/src/main/java/net/kyori/adventure/util/HSVLike.java
api/src/test/java/net/kyori/adventure/text/BlockNBTComponentTest.java
api/src/test/java/net/kyori/adventure/text/format/StyleTest.java
api/src/test/java/net/kyori/adventure/translation/GlobalTranslatorTest.java
api/src/test/java/net/kyori/adventure/util/HSVLikeTest.java
key/src/main/java/net/kyori/adventure/key/KeyedValue.java
key/src/test/java/net/kyori/adventure/key/KeyedValueTest.java
serializer-configurate3/src/main/java/net/kyori/adventure/serializer/configurate3/HoverEventShowItemSerializer.java
serializer-configurate3/src/test/java/net/kyori/adventure/serializer/configurate3/HoverEventSerializersTest.java
serializer-configurate4/src/main/java/net/kyori/adventure/serializer/configurate4/HoverEventShowItemSerializer.java
serializer-configurate4/src/test/java/net/kyori/adventure/serializer/configurate4/HoverEventSerializersTest.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/transformation/inbuild/HoverTransformation.java
text-serializer-gson-legacy-impl/src/main/java/net/kyori/adventure/text/serializer/gson/legacyimpl/NBTLegacyHoverEventSerializerImpl.java
text-serializer-gson/src/jmh/java/net/kyori/adventure/text/serializer/gson/ComponentDeserializationBenchmark.java
text-serializer-gson/src/jmh/java/net/kyori/adventure/text/serializer/gson/ComponentSerializationBenchmark.java
text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/ShowItemSerializer.java
text-serializer-gson/src/test/java/net/kyori/adventure/text/serializer/gson/ShowItemSerializerTest.java

Adresses all points in #454 except for `adventure-nbt` and the two in `HoverEvent`

chore: Rename some static constructer methods

---

text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/MiniMessage.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/MiniMessageImpl.java
text-minimessage/src/main/java/net/kyori/adventure/text/minimessage/MiniMessageParser.java
text-minimessage/src/test/java/net/kyori/adventure/text/minimessage/MiniMessageParserTest.java

Related to KyoriPowered/adventure-webui#68.
Introduces a method returning the `ElementNode` tree, right before it would be turned into a component.
As this is mostly a debug feature with not much actual practical use, I'm wondering if it should somehow be more hidden in the API...

text-minimessage: add deserialization method returning parsed tree

---

api/src/main/java/net/kyori/adventure/text/JoinConfiguration.java
api/src/main/java/net/kyori/adventure/text/JoinConfigurationImpl.java
api/src/test/java/net/kyori/adventure/text/JoinTest.java

feat(api): Add possibility of using Component#join with a root style

---

api/src/main/java/net/kyori/adventure/text/format/DecorationMap.java
api/src/main/java/net/kyori/adventure/text/format/Style.java
api/src/main/java/net/kyori/adventure/text/format/StyleImpl.java

Reduces code repetition in `StyleImpl` by implementing a `DecorationMap`, a `Map<TextDecoration, TextDecoration.State>` that operates on bit flags.
Closes #392

StyleImpl DRY (#392)

---

api/src/main/java/net/kyori/adventure/pointer/PointersSupplier.java
api/src/main/java/net/kyori/adventure/pointer/PointersSupplierImpl.java
api/src/test/java/net/kyori/adventure/pointer/PointersTest.java

This PR closes #428 by providing the `PointersSupplier` class which can be stored statically and resolved whenever `Audience#pointers()` is called to prevent having a bazillion hash maps lying about that all do the same thing.
When implemented, it would look something like this:
```java
public class MyPointeredObject extends SomePointeredParent implements Pointered {
private static final PointersSupplier<MyPointeredObject> POINTERS = PointersSupplier.builder()
.parent(SomePointeredParent.POINTERS) // Fallback to the parent to get pointers from.
.resolving(Identity.UUID, MyPointeredObject::getUniqueId)
.resolving(Identity.DISPLAY_NAME, MyPointeredObject::getDisplayName)
.build();
@Override
public Pointers pointers() {
return POINTERS.view(this);
}
}
```

 feat(api): Pointers supplier
